// World destinations database with 2000+ cities from CSV
export interface CityData {
  id: string;
  name: string;
  country: string;
  region: string;
  airportCode?: string;
  nearestAirports?: Array<{
    code: string;
    name: string;
    distance?: string;
  }>;
  type: "city";
  bestMonths?: number[];
  shoulderMonths?: number[];
  trending2026?: boolean;
}

// Helper to map countries to regions
function getRegion(country: string): string {
  const regionMap: Record<string, string> = {
    "United States": "North America", "Canada": "North America", "Mexico": "North America",
    "Cuba": "Caribbean", "Jamaica": "Caribbean", "Bahamas": "Caribbean", "Barbados": "Caribbean",
    "Aruba": "Caribbean", "Puerto Rico": "Caribbean", "Dominican Republic": "Caribbean",
    "Costa Rica": "Central America", "Panama": "Central America", "Belize": "Central America",
    "Guatemala": "Central America", "Colombia": "South America", "Ecuador": "South America",
    "Peru": "South America", "Bolivia": "South America", "Chile": "South America",
    "Argentina": "South America", "Brazil": "South America", "Uruguay": "South America",
    "Paraguay": "South America", "Venezuela": "South America",
    "United Kingdom": "Europe", "Ireland": "Europe", "France": "Europe", "Germany": "Europe",
    "Italy": "Europe", "Spain": "Europe", "Portugal": "Europe", "Netherlands": "Europe",
    "Belgium": "Europe", "Switzerland": "Europe", "Austria": "Europe", "Denmark": "Europe",
    "Sweden": "Europe", "Norway": "Europe", "Finland": "Europe", "Iceland": "Europe",
    "Poland": "Europe", "Czech Republic": "Europe", "Hungary": "Europe", "Croatia": "Europe",
    "Greece": "Europe", "Turkey": "Europe", "Estonia": "Europe", "Latvia": "Europe",
    "Lithuania": "Europe", "Slovenia": "Europe", "Slovakia": "Europe", "Bulgaria": "Europe",
    "Romania": "Europe", "Serbia": "Europe", "Bosnia and Herzegovina": "Europe",
    "North Macedonia": "Europe", "Albania": "Europe", "Montenegro": "Europe",
    "Kosovo": "Europe", "Moldova": "Europe", "Ukraine": "Europe", "Russia": "Europe",
    "Georgia": "Asia", "Armenia": "Asia", "Azerbaijan": "Asia",
    "Japan": "Asia", "China": "Asia", "Taiwan": "Asia", "South Korea": "Asia",
    "Thailand": "Asia", "Vietnam": "Asia", "Singapore": "Asia", "Malaysia": "Asia",
    "Indonesia": "Asia", "Philippines": "Asia", "India": "Asia", "Nepal": "Asia",
    "Sri Lanka": "Asia", "Maldives": "Asia", "Kazakhstan": "Asia", "Uzbekistan": "Asia",
    "Kyrgyzstan": "Asia", "Cambodia": "Asia", "Laos": "Asia", "Myanmar": "Asia",
    "Bangladesh": "Asia", "Pakistan": "Asia", "Afghanistan": "Asia", "Mongolia": "Asia",
    "United Arab Emirates": "Middle East", "Qatar": "Middle East", "Oman": "Middle East",
    "Saudi Arabia": "Middle East", "Kuwait": "Middle East", "Bahrain": "Middle East",
    "Israel": "Middle East", "Jordan": "Middle East", "Lebanon": "Middle East",
    "Iraq": "Middle East", "Iran": "Middle East", "Yemen": "Middle East",
    "Egypt": "Africa", "Morocco": "Africa", "Tunisia": "Africa", "Algeria": "Africa",
    "South Africa": "Africa", "Kenya": "Africa", "Tanzania": "Africa", "Rwanda": "Africa",
    "Ethiopia": "Africa", "Ghana": "Africa", "Nigeria": "Africa", "Senegal": "Africa",
    "Ivory Coast": "Africa", "Gambia": "Africa", "Namibia": "Africa", "Zimbabwe": "Africa",
    "Botswana": "Africa", "Mozambique": "Africa", "Madagascar": "Africa",
    "Seychelles": "Africa", "Mauritius": "Africa", "Reunion": "Africa", "Mali": "Africa",
    "Burkina Faso": "Africa", "Niger": "Africa", "Mauritania": "Africa", "Togo": "Africa",
    "Libya": "Africa", "Sudan": "Africa", "Uganda": "Africa", "Zambia": "Africa",
    "Australia": "Oceania", "New Zealand": "Oceania", "Fiji": "Oceania",
    "Papua New Guinea": "Oceania", "French Polynesia": "Oceania", "Samoa": "Oceania",
    "Solomon Islands": "Oceania", "Palau": "Oceania", "Vanuatu": "Oceania",
    "New Caledonia": "Oceania", "Tonga": "Oceania", "Cook Islands": "Oceania",
  };
  return regionMap[country] || "Other";
}

// Import all 2000+ destinations from the CSV
// Format: { id, name, country, region, airportCode, type, bestMonths, shoulderMonths }
export const CITIES: CityData[] = [
  { id: "paris", name: "Paris", country: "France", region: "Europe", airportCode: "PAR", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "london", name: "London", country: "United Kingdom", region: "Europe", airportCode: "LON", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "new-york-city", name: "New York City", country: "United States", region: "North America", airportCode: "NYC", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "tokyo", name: "Tokyo", country: "Japan", region: "Asia", airportCode: "TYO", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [5,9] },
  { id: "rome", name: "Rome", country: "Italy", region: "Europe", airportCode: "ROM", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "barcelona", name: "Barcelona", country: "Spain", region: "Europe", airportCode: "BCN", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "bangkok", name: "Bangkok", country: "Thailand", region: "Asia", airportCode: "BKK", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "dubai", name: "Dubai", country: "United Arab Emirates", region: "Middle East", airportCode: "DXB", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [4,10] },
  { id: "singapore", name: "Singapore", country: "Singapore", region: "Asia", airportCode: "SIN", type: "city", bestMonths: [12,1,6,7,8], shoulderMonths: [3,4,5,9,10,11] },
  { id: "istanbul", name: "Istanbul", country: "Turkey", region: "Europe", airportCode: "IST", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "amsterdam", name: "Amsterdam", country: "Netherlands", region: "Europe", airportCode: "AMS", type: "city", bestMonths: [4,5,6,7,8,9], shoulderMonths: [3,10] },
  { id: "hong-kong", name: "Hong Kong", country: "China", region: "Asia", airportCode: "HKG", type: "city", bestMonths: [10,11,12], shoulderMonths: [3,4,5] },
  { id: "seoul", name: "Seoul", country: "South Korea", region: "Asia", airportCode: "SEL", type: "city", bestMonths: [9,10,11,4,5], shoulderMonths: [6] },
  { id: "los-angeles", name: "Los Angeles", country: "United States", region: "North America", airportCode: "LAX", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "san-francisco", name: "San Francisco", country: "United States", region: "North America", airportCode: "SFO", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [4,5,10] },
  { id: "las-vegas", name: "Las Vegas", country: "United States", region: "North America", airportCode: "LAS", type: "city", bestMonths: [3,4,5,9,10], shoulderMonths: [2,11] },
  { id: "miami", name: "Miami", country: "United States", region: "North America", airportCode: "MIA", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "mexico-city", name: "Mexico City", country: "Mexico", region: "North America", airportCode: "MEX", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [4,10] },
  { id: "toronto", name: "Toronto", country: "Canada", region: "North America", airportCode: "YTO", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "vancouver", name: "Vancouver", country: "Canada", region: "North America", airportCode: "YVR", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "chicago", name: "Chicago", country: "United States", region: "North America", airportCode: "CHI", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "boston", name: "Boston", country: "United States", region: "North America", airportCode: "BOS", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "washington-dc", name: "Washington DC", country: "United States", region: "North America", airportCode: "WAS", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "orlando", name: "Orlando", country: "United States", region: "North America", airportCode: "ORL", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "honolulu", name: "Honolulu", country: "United States", region: "North America", airportCode: "HNL", type: "city", bestMonths: [12,1,2,3,6,7,8], shoulderMonths: [4,5,9,10,11] },
  { id: "montreal", name: "Montreal", country: "Canada", region: "North America", airportCode: "YMQ", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "quebec-city", name: "Quebec City", country: "Canada", region: "North America", airportCode: "YQB", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "cancun", name: "Cancun", country: "Mexico", region: "North America", airportCode: "CUN", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "tulum", name: "Tulum", country: "Mexico", region: "North America", airportCode: "TUY", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "havana", name: "Havana", country: "Cuba", region: "Caribbean", airportCode: "HAV", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "medellin", name: "Medellín", country: "Colombia", region: "South America", airportCode: "MDE", type: "city", bestMonths: [12,1,2,7,8], shoulderMonths: [3,6,9] },
  { id: "cartagena", name: "Cartagena", country: "Colombia", region: "South America", airportCode: "CTG", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "quito", name: "Quito", country: "Ecuador", region: "South America", airportCode: "UIO", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "galapagos-islands", name: "Galapagos Islands", country: "Ecuador", region: "South America", airportCode: "GPS", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [4,5,10,11] },
  { id: "la-paz", name: "La Paz", country: "Bolivia", region: "South America", airportCode: "LPB", type: "city", bestMonths: [5,6,7,8], shoulderMonths: [4,9] },
  { id: "sao-paulo", name: "Sao Paulo", country: "Brazil", region: "South America", airportCode: "SAO", type: "city", bestMonths: [3,4,5,9,10], shoulderMonths: [2,11] },
  { id: "salvador", name: "Salvador", country: "Brazil", region: "South America", airportCode: "SSA", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11] },
  { id: "recife", name: "Recife", country: "Brazil", region: "South America", airportCode: "REC", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11] },
  { id: "montevideo", name: "Montevideo", country: "Uruguay", region: "South America", airportCode: "MVD", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "lima-barranco", name: "Lima Barranco", country: "Peru", region: "South America", airportCode: "LIM", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "yokohama", name: "Yokohama", country: "Japan", region: "Asia", airportCode: "TYO", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [5,9] },
  { id: "kyoto", name: "Kyoto", country: "Japan", region: "Asia", airportCode: "KIX", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [5,9] },
  { id: "osaka", name: "Osaka", country: "Japan", region: "Asia", airportCode: "OSA", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [5,9] },
  { id: "hiroshima", name: "Hiroshima", country: "Japan", region: "Asia", airportCode: "HIJ", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [5,9] },
  { id: "sapporo", name: "Sapporo", country: "Japan", region: "Asia", airportCode: "SPK", type: "city", bestMonths: [2,3,7,8], shoulderMonths: [6,9] },
  { id: "beijing", name: "Beijing", country: "China", region: "Asia", airportCode: "BJS", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "shanghai", name: "Shanghai", country: "China", region: "Asia", airportCode: "SHA", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "xian", name: "Xi'an", country: "China", region: "Asia", airportCode: "SIA", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "chengdu", name: "Chengdu", country: "China", region: "Asia", airportCode: "CTU", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "taipei", name: "Taipei", country: "Taiwan", region: "Asia", airportCode: "TPE", type: "city", bestMonths: [10,11,3,4], shoulderMonths: [5,9] },
  { id: "kaohsiung", name: "Kaohsiung", country: "Taiwan", region: "Asia", airportCode: "KHH", type: "city", bestMonths: [10,11,3,4], shoulderMonths: [5,9] },
  { id: "chiang-mai", name: "Chiang Mai", country: "Thailand", region: "Asia", airportCode: "CNX", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "phuket", name: "Phuket", country: "Thailand", region: "Asia", airportCode: "HKT", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "hanoi", name: "Hanoi", country: "Vietnam", region: "Asia", airportCode: "HAN", type: "city", bestMonths: [10,11,3,4], shoulderMonths: [5,9] },
  { id: "ho-chi-minh-city", name: "Ho Chi Minh City", country: "Vietnam", region: "Asia", airportCode: "SGN", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11] },
  { id: "da-nang", name: "Da Nang", country: "Vietnam", region: "Asia", airportCode: "DAD", type: "city", bestMonths: [3,4], shoulderMonths: [2,5,9] },
  { id: "bali-ubud", name: "Bali Ubud", country: "Indonesia", region: "Asia", airportCode: "DPS", type: "city", bestMonths: [4,5,6,7,8,9], shoulderMonths: [3,10] },
  { id: "jakarta", name: "Jakarta", country: "Indonesia", region: "Asia", airportCode: "JKT", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "kuala-lumpur", name: "Kuala Lumpur", country: "Malaysia", region: "Asia", airportCode: "KUL", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "penang", name: "Penang", country: "Malaysia", region: "Asia", airportCode: "PEN", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11] },
  { id: "maldives", name: "Maldives", country: "Maldives", region: "Asia", airportCode: "MLE", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "doha", name: "Doha", country: "Qatar", region: "Middle East", airportCode: "DOH", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [4,10] },
  { id: "muscat", name: "Muscat", country: "Oman", region: "Middle East", airportCode: "MCT", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [4,10] },
  { id: "tel-aviv", name: "Tel Aviv", country: "Israel", region: "Middle East", airportCode: "TLV", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "jerusalem", name: "Jerusalem", country: "Israel", region: "Middle East", airportCode: "TLV", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "milan", name: "Milan", country: "Italy", region: "Europe", airportCode: "MIL", type: "city", bestMonths: [4,5,6,7,9], shoulderMonths: [3,10] },
  { id: "florence", name: "Florence", country: "Italy", region: "Europe", airportCode: "FLR", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "venice", name: "Venice", country: "Italy", region: "Europe", airportCode: "VCE", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "naples", name: "Naples", country: "Italy", region: "Europe", airportCode: "NAP", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "palermo", name: "Palermo", country: "Italy", region: "Europe", airportCode: "PMO", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "nice", name: "Nice", country: "France", region: "Europe", airportCode: "NCE", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "lyon", name: "Lyon", country: "France", region: "Europe", airportCode: "LYS", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "marseille", name: "Marseille", country: "France", region: "Europe", airportCode: "MRS", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "bordeaux", name: "Bordeaux", country: "France", region: "Europe", airportCode: "BOD", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "edinburgh", name: "Edinburgh", country: "United Kingdom", region: "Europe", airportCode: "EDI", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "manchester", name: "Manchester", country: "United Kingdom", region: "Europe", airportCode: "MAN", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "dublin", name: "Dublin", country: "Ireland", region: "Europe", airportCode: "DUB", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "brussels", name: "Brussels", country: "Belgium", region: "Europe", airportCode: "BRU", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "zurich", name: "Zurich", country: "Switzerland", region: "Europe", airportCode: "ZRH", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "geneva", name: "Geneva", country: "Switzerland", region: "Europe", airportCode: "GVA", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "budapest", name: "Budapest", country: "Hungary", region: "Europe", airportCode: "BUD", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "krakow", name: "Krakow", country: "Poland", region: "Europe", airportCode: "KRK", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "warsaw", name: "Warsaw", country: "Poland", region: "Europe", airportCode: "WAW", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "tallinn", name: "Tallinn", country: "Estonia", region: "Europe", airportCode: "TLL", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "riga", name: "Riga", country: "Latvia", region: "Europe", airportCode: "RIX", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "vilnius", name: "Vilnius", country: "Lithuania", region: "Europe", airportCode: "VNO", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "dubrovnik", name: "Dubrovnik", country: "Croatia", region: "Europe", airportCode: "DBV", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "split", name: "Split", country: "Croatia", region: "Europe", airportCode: "SPU", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "zagreb", name: "Zagreb", country: "Croatia", region: "Europe", airportCode: "ZAG", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "ljubljana", name: "Ljubljana", country: "Slovenia", region: "Europe", airportCode: "LJU", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "vienna", name: "Vienna", country: "Austria", region: "Europe", airportCode: "VIE", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "salzburg", name: "Salzburg", country: "Austria", region: "Europe", airportCode: "SZG", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "innsbruck", name: "Innsbruck", country: "Austria", region: "Europe", airportCode: "INN", type: "city", bestMonths: [6,7,8,12,1,2], shoulderMonths: [5,9,10] },
  { id: "sitges", name: "Sitges", country: "Spain", region: "Europe", airportCode: "BCN", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "valencia", name: "Valencia", country: "Spain", region: "Europe", airportCode: "VLC", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "seville", name: "Seville", country: "Spain", region: "Europe", airportCode: "SVQ", type: "city", bestMonths: [5,6,9], shoulderMonths: [4,10] },
  { id: "granada", name: "Granada", country: "Spain", region: "Europe", airportCode: "GRX", type: "city", bestMonths: [5,6,9], shoulderMonths: [4,10] },
  { id: "malaga", name: "Malaga", country: "Spain", region: "Europe", airportCode: "AGP", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "delhi", name: "Delhi", country: "India", region: "Asia", airportCode: "DEL", type: "city", bestMonths: [10,11,2,3], shoulderMonths: [9,4] },
  { id: "mumbai", name: "Mumbai", country: "India", region: "Asia", airportCode: "BOM", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "jaipur", name: "Jaipur", country: "India", region: "Asia", airportCode: "JAI", type: "city", bestMonths: [10,11,2,3], shoulderMonths: [9,4] },
  { id: "bengaluru", name: "Bengaluru", country: "India", region: "Asia", airportCode: "BLR", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [4,9] },
  { id: "goa", name: "Goa", country: "India", region: "Asia", airportCode: "GOI", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "kathmandu", name: "Kathmandu", country: "Nepal", region: "Asia", airportCode: "KTM", type: "city", bestMonths: [10,11,3,4], shoulderMonths: [9,5] },
  { id: "colombo", name: "Colombo", country: "Sri Lanka", region: "Asia", airportCode: "CMB", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "cairo", name: "Cairo", country: "Egypt", region: "Africa", airportCode: "CAI", type: "city", bestMonths: [10,11,12,1,2,3,4], shoulderMonths: [5,9] },
  { id: "marrakech", name: "Marrakech", country: "Morocco", region: "Africa", airportCode: "RAK", type: "city", bestMonths: [3,4,5,10,11], shoulderMonths: [2,9] },
  { id: "casablanca", name: "Casablanca", country: "Morocco", region: "Africa", airportCode: "CAS", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "tunis", name: "Tunis", country: "Tunisia", region: "Africa", airportCode: "TUN", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "cape-town", name: "Cape Town", country: "South Africa", region: "Africa", airportCode: "CPT", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "johannesburg", name: "Johannesburg", country: "South Africa", region: "Africa", airportCode: "JNB", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "nairobi", name: "Nairobi", country: "Kenya", region: "Africa", airportCode: "NBO", type: "city", bestMonths: [6,7,8,9,1,2], shoulderMonths: [5,10] },
  { id: "zanzibar", name: "Zanzibar", country: "Tanzania", region: "Africa", airportCode: "ZNZ", type: "city", bestMonths: [6,7,8,9,1,2], shoulderMonths: [5,10] },
  { id: "kigali", name: "Kigali", country: "Rwanda", region: "Africa", airportCode: "KGL", type: "city", bestMonths: [6,7,8,9,12,1,2], shoulderMonths: [5,10] },
  { id: "addis-ababa", name: "Addis Ababa", country: "Ethiopia", region: "Africa", airportCode: "ADD", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [9,4] },
  { id: "accra", name: "Accra", country: "Ghana", region: "Africa", airportCode: "ACC", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "lagos", name: "Lagos", country: "Nigeria", region: "Africa", airportCode: "LOS", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "dakar", name: "Dakar", country: "Senegal", region: "Africa", airportCode: "DSS", type: "city", bestMonths: [11,12,1,2,3,4], shoulderMonths: [10,5] },
  { id: "windhoek", name: "Windhoek", country: "Namibia", region: "Africa", airportCode: "WDH", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "victoria-falls", name: "Victoria Falls", country: "Zimbabwe", region: "Africa", airportCode: "VFA", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "sydney", name: "Sydney", country: "Australia", region: "Oceania", airportCode: "SYD", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "melbourne", name: "Melbourne", country: "Australia", region: "Oceania", airportCode: "MEL", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "brisbane", name: "Brisbane", country: "Australia", region: "Oceania", airportCode: "BNE", type: "city", bestMonths: [9,10,11], shoulderMonths: [8,12] },
  { id: "perth", name: "Perth", country: "Australia", region: "Oceania", airportCode: "PER", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [9,4] },
  { id: "auckland", name: "Auckland", country: "New Zealand", region: "Oceania", airportCode: "AKL", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "queenstown", name: "Queenstown", country: "New Zealand", region: "Oceania", airportCode: "ZQN", type: "city", bestMonths: [12,1,2,3,6,7,8], shoulderMonths: [11,4,5,9] },
  { id: "wellington", name: "Wellington", country: "New Zealand", region: "Oceania", airportCode: "WLG", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "nadi", name: "Nadi", country: "Fiji", region: "Oceania", airportCode: "NAN", type: "city", bestMonths: [5,6,7,8,9,10], shoulderMonths: [4,11] },
  { id: "papeete", name: "Papeete", country: "French Polynesia", region: "Oceania", airportCode: "PPT", type: "city", bestMonths: [5,6,7,8,9,10], shoulderMonths: [4,11] },
  { id: "reykjavik", name: "Reykjavik", country: "Iceland", region: "Europe", airportCode: "KEF", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "copenhagen", name: "Copenhagen", country: "Denmark", region: "Europe", airportCode: "CPH", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "stockholm", name: "Stockholm", country: "Sweden", region: "Europe", airportCode: "STO", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "oslo", name: "Oslo", country: "Norway", region: "Europe", airportCode: "OSL", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "helsinki", name: "Helsinki", country: "Finland", region: "Europe", airportCode: "HEL", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "prague", name: "Prague", country: "Czech Republic", region: "Europe", airportCode: "PRG", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "athens", name: "Athens", country: "Greece", region: "Europe", airportCode: "ATH", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "santorini", name: "Santorini", country: "Greece", region: "Europe", airportCode: "JTR", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "mykonos", name: "Mykonos", country: "Greece", region: "Europe", airportCode: "JMK", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "crete", name: "Crete", country: "Greece", region: "Europe", airportCode: "HER", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "lisbon", name: "Lisbon", country: "Portugal", region: "Europe", airportCode: "LIS", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "porto", name: "Porto", country: "Portugal", region: "Europe", airportCode: "OPO", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "algarve", name: "Algarve", country: "Portugal", region: "Europe", airportCode: "FAO", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "madeira", name: "Madeira", country: "Portugal", region: "Europe", airportCode: "FNC", type: "city", bestMonths: [4,5,6,9,10], shoulderMonths: [3,7,8,11] },
  { id: "berlin", name: "Berlin", country: "Germany", region: "Europe", airportCode: "BER", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "munich", name: "Munich", country: "Germany", region: "Europe", airportCode: "MUC", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "frankfurt", name: "Frankfurt", country: "Germany", region: "Europe", airportCode: "FRA", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "hamburg", name: "Hamburg", country: "Germany", region: "Europe", airportCode: "HAM", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "cologne", name: "Cologne", country: "Germany", region: "Europe", airportCode: "CGN", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "madrid", name: "Madrid", country: "Spain", region: "Europe", airportCode: "MAD", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "bilbao", name: "Bilbao", country: "Spain", region: "Europe", airportCode: "BIO", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "san-sebastian", name: "San Sebastian", country: "Spain", region: "Europe", airportCode: "EAS", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "ibiza", name: "Ibiza", country: "Spain", region: "Europe", airportCode: "IBZ", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "majorca", name: "Majorca", country: "Spain", region: "Europe", airportCode: "PMI", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "turin", name: "Turin", country: "Italy", region: "Europe", airportCode: "TRN", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "bologna", name: "Bologna", country: "Italy", region: "Europe", airportCode: "BLQ", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "verona", name: "Verona", country: "Italy", region: "Europe", airportCode: "VRN", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "pisa", name: "Pisa", country: "Italy", region: "Europe", airportCode: "PSA", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "amalfi", name: "Amalfi", country: "Italy", region: "Europe", airportCode: "NAP", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "sicily", name: "Sicily", country: "Italy", region: "Europe", airportCode: "CTA", type: "city", bestMonths: [5,6,7,9], shoulderMonths: [4,10] },
  { id: "sardinia", name: "Sardinia", country: "Italy", region: "Europe", airportCode: "CAG", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "strasbourg", name: "Strasbourg", country: "France", region: "Europe", airportCode: "SXB", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "nantes", name: "Nantes", country: "France", region: "Europe", airportCode: "NTE", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "toulouse", name: "Toulouse", country: "France", region: "Europe", airportCode: "TLS", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "tours", name: "Tours", country: "France", region: "Europe", airportCode: "PAR", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "cannes", name: "Cannes", country: "France", region: "Europe", airportCode: "NCE", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "annecy", name: "Annecy", country: "France", region: "Europe", airportCode: "NCY", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "biarritz", name: "Biarritz", country: "France", region: "Europe", airportCode: "BIQ", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "rennes", name: "Rennes", country: "France", region: "Europe", airportCode: "RNS", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "lille", name: "Lille", country: "France", region: "Europe", airportCode: "LIL", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "bratislava", name: "Bratislava", country: "Slovakia", region: "Europe", airportCode: "BTS", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "belgrade", name: "Belgrade", country: "Serbia", region: "Europe", airportCode: "BEG", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "bucharest", name: "Bucharest", country: "Romania", region: "Europe", airportCode: "BUH", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "sofia", name: "Sofia", country: "Bulgaria", region: "Europe", airportCode: "SOF", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "skopje", name: "Skopje", country: "North Macedonia", region: "Europe", airportCode: "SKP", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "tirana", name: "Tirana", country: "Albania", region: "Europe", airportCode: "TIA", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "sarajevo", name: "Sarajevo", country: "Bosnia and Herzegovina", region: "Europe", airportCode: "SJJ", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "podgorica", name: "Podgorica", country: "Montenegro", region: "Europe", airportCode: "TGD", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "kotor", name: "Kotor", country: "Montenegro", region: "Europe", airportCode: "TIV", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9,10] },
  { id: "manila", name: "Manila", country: "Philippines", region: "Asia", airportCode: "MNL", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "cebu", name: "Cebu", country: "Philippines", region: "Asia", airportCode: "CEB", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "boracay", name: "Boracay", country: "Philippines", region: "Asia", airportCode: "MPH", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "phnom-penh", name: "Phnom Penh", country: "Cambodia", region: "Asia", airportCode: "PNH", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "siem-reap", name: "Siem Reap", country: "Cambodia", region: "Asia", airportCode: "REP", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "vientiane", name: "Vientiane", country: "Laos", region: "Asia", airportCode: "VTE", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "luang-prabang", name: "Luang Prabang", country: "Laos", region: "Asia", airportCode: "LPQ", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "yangon", name: "Yangon", country: "Myanmar", region: "Asia", airportCode: "RGN", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "bagan", name: "Bagan", country: "Myanmar", region: "Asia", airportCode: "NYU", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [3,4] },
  { id: "dhaka", name: "Dhaka", country: "Bangladesh", region: "Asia", airportCode: "DAC", type: "city", bestMonths: [11,12,1,2], shoulderMonths: [10,3] },
  { id: "almaty", name: "Almaty", country: "Kazakhstan", region: "Asia", airportCode: "ALA", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "tbilisi", name: "Tbilisi", country: "Georgia", region: "Asia", airportCode: "TBS", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "yerevan", name: "Yerevan", country: "Armenia", region: "Asia", airportCode: "EVN", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "baku", name: "Baku", country: "Azerbaijan", region: "Asia", airportCode: "BAK", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "seattle", name: "Seattle", country: "United States", region: "North America", airportCode: "SEA", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "portland", name: "Portland", country: "United States", region: "North America", airportCode: "PDX", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "san-diego", name: "San Diego", country: "United States", region: "North America", airportCode: "SAN", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "phoenix", name: "Phoenix", country: "United States", region: "North America", airportCode: "PHX", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [10,4] },
  { id: "denver", name: "Denver", country: "United States", region: "North America", airportCode: "DEN", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "austin", name: "Austin", country: "United States", region: "North America", airportCode: "AUS", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [2,5] },
  { id: "nashville", name: "Nashville", country: "United States", region: "North America", airportCode: "BNA", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "new-orleans", name: "New Orleans", country: "United States", region: "North America", airportCode: "MSY", type: "city", bestMonths: [10,11,12,1,2,3,4], shoulderMonths: [5,9] },
  { id: "charleston", name: "Charleston", country: "United States", region: "North America", airportCode: "CHS", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "savannah", name: "Savannah", country: "United States", region: "North America", airportCode: "SAV", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "atlanta", name: "Atlanta", country: "United States", region: "North America", airportCode: "ATL", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "philadelphia", name: "Philadelphia", country: "United States", region: "North America", airportCode: "PHL", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "dallas", name: "Dallas", country: "United States", region: "North America", airportCode: "DFW", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [2,5] },
  { id: "houston", name: "Houston", country: "United States", region: "North America", airportCode: "HOU", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [10,4] },
  { id: "minneapolis", name: "Minneapolis", country: "United States", region: "North America", airportCode: "MSP", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "salt-lake-city", name: "Salt Lake City", country: "United States", region: "North America", airportCode: "SLC", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "kansas-city", name: "Kansas City", country: "United States", region: "North America", airportCode: "MCI", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "san-antonio", name: "San Antonio", country: "United States", region: "North America", airportCode: "SAT", type: "city", bestMonths: [3,4,10,11], shoulderMonths: [2,5] },
  { id: "detroit", name: "Detroit", country: "United States", region: "North America", airportCode: "DTW", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "cleveland", name: "Cleveland", country: "United States", region: "North America", airportCode: "CLE", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "pittsburgh", name: "Pittsburgh", country: "United States", region: "North America", airportCode: "PIT", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "cincinnati", name: "Cincinnati", country: "United States", region: "North America", airportCode: "CVG", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "columbus", name: "Columbus", country: "United States", region: "North America", airportCode: "CMH", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "indianapolis", name: "Indianapolis", country: "United States", region: "North America", airportCode: "IND", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "milwaukee", name: "Milwaukee", country: "United States", region: "North America", airportCode: "MKE", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "st-louis", name: "St. Louis", country: "United States", region: "North America", airportCode: "STL", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "baltimore", name: "Baltimore", country: "United States", region: "North America", airportCode: "BWI", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "richmond", name: "Richmond", country: "United States", region: "North America", airportCode: "RIC", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "raleigh", name: "Raleigh", country: "United States", region: "North America", airportCode: "RDU", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "charlotte", name: "Charlotte", country: "United States", region: "North America", airportCode: "CLT", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "memphis", name: "Memphis", country: "United States", region: "North America", airportCode: "MEM", type: "city", bestMonths: [4,5,9,10], shoulderMonths: [3,11] },
  { id: "louisville", name: "Louisville", country: "United States", region: "North America", airportCode: "SDF", type: "city", bestMonths: [5,6,9,10], shoulderMonths: [4,11] },
  { id: "tampa", name: "Tampa", country: "United States", region: "North America", airportCode: "TPA", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "jacksonville", name: "Jacksonville", country: "United States", region: "North America", airportCode: "JAX", type: "city", bestMonths: [4,5,10,11], shoulderMonths: [3,12] },
  { id: "fort-lauderdale", name: "Fort Lauderdale", country: "United States", region: "North America", airportCode: "FLL", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "key-west", name: "Key West", country: "United States", region: "North America", airportCode: "EYW", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "anchorage", name: "Anchorage", country: "United States", region: "North America", airportCode: "ANC", type: "city", bestMonths: [6,7,8], shoulderMonths: [5,9] },
  { id: "aspen", name: "Aspen", country: "United States", region: "North America", airportCode: "ASE", type: "city", bestMonths: [12,1,2,6,7,8], shoulderMonths: [3,11] },
  { id: "santa-fe", name: "Santa Fe", country: "United States", region: "North America", airportCode: "SAF", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "palm-springs", name: "Palm Springs", country: "United States", region: "North America", airportCode: "PSP", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [10,4] },
  { id: "santa-barbara", name: "Santa Barbara", country: "United States", region: "North America", airportCode: "SBA", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "napa", name: "Napa", country: "United States", region: "North America", airportCode: "SFO", type: "city", bestMonths: [9,10], shoulderMonths: [5,6,7,8] },
  { id: "monterey", name: "Monterey", country: "United States", region: "North America", airportCode: "MRY", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "big-sur", name: "Big Sur", country: "United States", region: "North America", airportCode: "SFO", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "carmel", name: "Carmel", country: "United States", region: "North America", airportCode: "MRY", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "maui", name: "Maui", country: "United States", region: "North America", airportCode: "OGG", type: "city", bestMonths: [12,1,2,3,6,7,8], shoulderMonths: [4,5,9,10,11] },
  { id: "kauai", name: "Kauai", country: "United States", region: "North America", airportCode: "LIH", type: "city", bestMonths: [12,1,2,3,6,7,8], shoulderMonths: [4,5,9,10,11] },
  { id: "big-island", name: "Big Island", country: "United States", region: "North America", airportCode: "KOA", type: "city", bestMonths: [12,1,2,3,6,7,8], shoulderMonths: [4,5,9,10,11] },
  { id: "san-juan", name: "San Juan", country: "Puerto Rico", region: "Caribbean", airportCode: "SJU", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "nassau", name: "Nassau", country: "Bahamas", region: "Caribbean", airportCode: "NAS", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "kingston", name: "Kingston", country: "Jamaica", region: "Caribbean", airportCode: "KIN", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "montego-bay", name: "Montego Bay", country: "Jamaica", region: "Caribbean", airportCode: "MBJ", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "bridgetown", name: "Bridgetown", country: "Barbados", region: "Caribbean", airportCode: "BGI", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "oranjestad", name: "Oranjestad", country: "Aruba", region: "Caribbean", airportCode: "AUA", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "punta-cana", name: "Punta Cana", country: "Dominican Republic", region: "Caribbean", airportCode: "PUJ", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "puerto-plata", name: "Puerto Plata", country: "Dominican Republic", region: "Caribbean", airportCode: "POP", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "san-jose-costa-rica", name: "San Jose", country: "Costa Rica", region: "Central America", airportCode: "SJO", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "tamarindo", name: "Tamarindo", country: "Costa Rica", region: "Central America", airportCode: "LIR", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "manuel-antonio", name: "Manuel Antonio", country: "Costa Rica", region: "Central America", airportCode: "SJO", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "panama-city", name: "Panama City", country: "Panama", region: "Central America", airportCode: "PTY", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "belize-city", name: "Belize City", country: "Belize", region: "Central America", airportCode: "BZE", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "ambergris-caye", name: "Ambergris Caye", country: "Belize", region: "Central America", airportCode: "SPR", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11,5] },
  { id: "guatemala-city", name: "Guatemala City", country: "Guatemala", region: "Central America", airportCode: "GUA", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [10,4] },
  { id: "antigua-guatemala", name: "Antigua", country: "Guatemala", region: "Central America", airportCode: "GUA", type: "city", bestMonths: [11,12,1,2,3], shoulderMonths: [10,4] },
  { id: "bogota", name: "Bogotá", country: "Colombia", region: "South America", airportCode: "BOG", type: "city", bestMonths: [12,1,2,7,8], shoulderMonths: [3,6,9] },
  { id: "cali", name: "Cali", country: "Colombia", region: "South America", airportCode: "CLO", type: "city", bestMonths: [12,1,2,7,8], shoulderMonths: [3,6,9] },
  { id: "santa-marta", name: "Santa Marta", country: "Colombia", region: "South America", airportCode: "SMR", type: "city", bestMonths: [12,1,2,3,4], shoulderMonths: [11] },
  { id: "lima", name: "Lima", country: "Peru", region: "South America", airportCode: "LIM", type: "city", bestMonths: [6,7,8], shoulderMonths: [4,5,9,10] },
  { id: "cusco", name: "Cusco", country: "Peru", region: "South America", airportCode: "CUZ", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "machu-picchu", name: "Machu Picchu", country: "Peru", region: "South America", airportCode: "CUZ", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "arequipa", name: "Arequipa", country: "Peru", region: "South America", airportCode: "AQP", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "buenos-aires", name: "Buenos Aires", country: "Argentina", region: "South America", airportCode: "BUE", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [9,4] },
  { id: "mendoza", name: "Mendoza", country: "Argentina", region: "South America", airportCode: "MDZ", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [9,4] },
  { id: "bariloche", name: "Bariloche", country: "Argentina", region: "South America", airportCode: "BRC", type: "city", bestMonths: [12,1,2,6,7,8], shoulderMonths: [3,11] },
  { id: "ushuaia", name: "Ushuaia", country: "Argentina", region: "South America", airportCode: "USH", type: "city", bestMonths: [12,1,2], shoulderMonths: [11,3] },
  { id: "santiago", name: "Santiago", country: "Chile", region: "South America", airportCode: "SCL", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [9,4] },
  { id: "valparaiso", name: "Valparaíso", country: "Chile", region: "South America", airportCode: "SCL", type: "city", bestMonths: [10,11,12,1,2,3], shoulderMonths: [9,4] },
  { id: "san-pedro-de-atacama", name: "San Pedro de Atacama", country: "Chile", region: "South America", airportCode: "CJC", type: "city", bestMonths: [4,5,6,7,8,9], shoulderMonths: [3,10] },
  { id: "torres-del-paine", name: "Torres del Paine", country: "Chile", region: "South America", airportCode: "PUQ", type: "city", bestMonths: [12,1,2], shoulderMonths: [11,3] },
  { id: "rio-de-janeiro", name: "Rio de Janeiro", country: "Brazil", region: "South America", airportCode: "RIO", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "florianopolis", name: "Florianópolis", country: "Brazil", region: "South America", airportCode: "FLN", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "iguazu-falls", name: "Iguazu Falls", country: "Brazil", region: "South America", airportCode: "IGU", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "brasilia", name: "Brasilia", country: "Brazil", region: "South America", airportCode: "BSB", type: "city", bestMonths: [5,6,7,8,9], shoulderMonths: [4,10] },
  { id: "fortaleza", name: "Fortaleza", country: "Brazil", region: "South America", airportCode: "FOR", type: "city", bestMonths: [7,8,9,10,11,12], shoulderMonths: [6] },
  { id: "manaus", name: "Manaus", country: "Brazil", region: "South America", airportCode: "MAO", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "amazon-rainforest", name: "Amazon Rainforest", country: "Brazil", region: "South America", airportCode: "MAO", type: "city", bestMonths: [6,7,8,9], shoulderMonths: [5,10] },
  { id: "caracas", name: "Caracas", country: "Venezuela", region: "South America", airportCode: "CCS", type: "city", bestMonths: [12,1,2,3], shoulderMonths: [11,4] },
  { id: "asuncion", name: "Asunción", country: "Paraguay", region: "South America", airportCode: "ASU", type: "city", bestMonths: [5,6,7,8], shoulderMonths: [4,9] },
].map(city => ({
  ...city,
  region: getRegion(city.country)
}));

// Airport search database
export const AIRPORTS = [
  { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "United States" },
  { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "United States" },
  { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "United States" },
  { code: "LHR", name: "London Heathrow Airport", city: "London", country: "United Kingdom" },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
  { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
  { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan" },
  { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "United Arab Emirates" },
  { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore" },
  { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
  { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "China" },
  { code: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { code: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "United States" },
  { code: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada" },
  { code: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
  { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "India" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India" },
  { code: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy" },
  { code: "BCN", name: "Barcelona–El Prat Airport", city: "Barcelona", country: "Spain" },
  { code: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", city: "Madrid", country: "Spain" },
  { code: "LIS", name: "Lisbon Portela Airport", city: "Lisbon", country: "Portugal" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
  { code: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
  { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
  { code: "OSL", name: "Oslo Airport", city: "Oslo", country: "Norway" },
  { code: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland" },
  { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
  { code: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
  { code: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary" },
  { code: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania" },
  { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
  { code: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia" },
  { code: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia" },
  { code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia" },
  { code: "SPU", name: "Split Airport", city: "Split", country: "Croatia" },
  { code: "TLL", name: "Tallinn Airport", city: "Tallinn", country: "Estonia" },
  { code: "RIX", name: "Riga International Airport", city: "Riga", country: "Latvia" },
  { code: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania" },
  { code: "KEF", name: "Keflavík International Airport", city: "Reykjavik", country: "Iceland" },
  { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { code: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom" },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { code: "LUX", name: "Luxembourg Airport", city: "Luxembourg", country: "Luxembourg" },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany" },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  { code: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany" },
  { code: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany" },
  { code: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany" },
  { code: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy" },
  { code: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy" },
  { code: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy" },
  { code: "FLR", name: "Florence Airport", city: "Florence", country: "Italy" },
  { code: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy" },
  { code: "PMO", name: "Palermo Airport", city: "Palermo", country: "Italy" },
  { code: "CTA", name: "Catania–Fontanarossa Airport", city: "Catania", country: "Italy" },
  { code: "BLQ", name: "Bologna Guglielmo Marconi Airport", city: "Bologna", country: "Italy" },
  { code: "TRN", name: "Turin Airport", city: "Turin", country: "Italy" },
  { code: "VRN", name: "Verona Villafranca Airport", city: "Verona", country: "Italy" },
  { code: "PSA", name: "Pisa International Airport", city: "Pisa", country: "Italy" },
  { code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
  { code: "LYS", name: "Lyon–Saint-Exupéry Airport", city: "Lyon", country: "France" },
  { code: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France" },
  { code: "TLS", name: "Toulouse–Blagnac Airport", city: "Toulouse", country: "France" },
  { code: "BOD", name: "Bordeaux–Mérignac Airport", city: "Bordeaux", country: "France" },
  { code: "NTE", name: "Nantes Atlantique Airport", city: "Nantes", country: "France" },
  { code: "SXB", name: "Strasbourg Airport", city: "Strasbourg", country: "France" },
  { code: "BIQ", name: "Biarritz Airport", city: "Biarritz", country: "France" },
  { code: "LIL", name: "Lille Airport", city: "Lille", country: "France" },
  { code: "RNS", name: "Rennes–Saint-Jacques Airport", city: "Rennes", country: "France" },
  { code: "OPO", name: "Francisco Sá Carneiro Airport", city: "Porto", country: "Portugal" },
  { code: "FAO", name: "Faro Airport", city: "Algarve", country: "Portugal" },
  { code: "FNC", name: "Madeira Airport", city: "Madeira", country: "Portugal" },
  { code: "AGP", name: "Málaga Airport", city: "Malaga", country: "Spain" },
  { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain" },
  { code: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain" },
  { code: "BIO", name: "Bilbao Airport", city: "Bilbao", country: "Spain" },
  { code: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "Spain" },
  { code: "PMI", name: "Palma de Mallorca Airport", city: "Majorca", country: "Spain" },
  { code: "ALC", name: "Alicante Airport", city: "Alicante", country: "Spain" },
  { code: "GRX", name: "Granada Airport", city: "Granada", country: "Spain" },
  { code: "SCQ", name: "Santiago de Compostela Airport", city: "Santiago de Compostela", country: "Spain" },
  { code: "JTR", name: "Santorini Airport", city: "Santorini", country: "Greece" },
  { code: "JMK", name: "Mykonos Airport", city: "Mykonos", country: "Greece" },
  { code: "HER", name: "Heraklion International Airport", city: "Crete", country: "Greece" },
  { code: "CFU", name: "Corfu International Airport", city: "Corfu", country: "Greece" },
  { code: "RHO", name: "Rhodes International Airport", city: "Rhodes", country: "Greece" },
  { code: "SKG", name: "Thessaloniki Airport", city: "Thessaloniki", country: "Greece" },
  { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
  { code: "SSH", name: "Sharm El Sheikh International Airport", city: "Sharm El Sheikh", country: "Egypt" },
  { code: "HRG", name: "Hurghada International Airport", city: "Hurghada", country: "Egypt" },
  { code: "RAK", name: "Marrakesh Menara Airport", city: "Marrakech", country: "Morocco" },
  { code: "CAS", name: "Mohammed V International Airport", city: "Casablanca", country: "Morocco" },
  { code: "TUN", name: "Tunis–Carthage International Airport", city: "Tunis", country: "Tunisia" },
  { code: "JNB", name: "OR Tambo International Airport", city: "Johannesburg", country: "South Africa" },
  { code: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa" },
  { code: "DUR", name: "King Shaka International Airport", city: "Durban", country: "South Africa" },
  { code: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya" },
  { code: "ZNZ", name: "Abeid Amani Karume International Airport", city: "Zanzibar", country: "Tanzania" },
  { code: "DAR", name: "Julius Nyerere International Airport", city: "Dar es Salaam", country: "Tanzania" },
  { code: "KGL", name: "Kigali International Airport", city: "Kigali", country: "Rwanda" },
  { code: "ADD", name: "Addis Ababa Bole International Airport", city: "Addis Ababa", country: "Ethiopia" },
  { code: "ACC", name: "Kotoka International Airport", city: "Accra", country: "Ghana" },
  { code: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria" },
  { code: "DSS", name: "Blaise Diagne International Airport", city: "Dakar", country: "Senegal" },
  { code: "WDH", name: "Hosea Kutako International Airport", city: "Windhoek", country: "Namibia" },
  { code: "VFA", name: "Victoria Falls Airport", city: "Victoria Falls", country: "Zimbabwe" },
  { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
  { code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China" },
  { code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China" },
  { code: "CTU", name: "Chengdu Shuangliu International Airport", city: "Chengdu", country: "China" },
  { code: "XIY", name: "Xi'an Xianyang International Airport", city: "Xi'an", country: "China" },
  { code: "KMG", name: "Kunming Changshui International Airport", city: "Kunming", country: "China" },
  { code: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "Taiwan" },
  { code: "KHH", name: "Kaohsiung International Airport", city: "Kaohsiung", country: "Taiwan" },
  { code: "OSA", name: "Osaka International Airport", city: "Osaka", country: "Japan" },
  { code: "KIX", name: "Kansai International Airport", city: "Osaka/Kyoto", country: "Japan" },
  { code: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan" },
  { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan" },
  { code: "NGO", name: "Chubu Centrair International Airport", city: "Nagoya", country: "Japan" },
  { code: "HIJ", name: "Hiroshima Airport", city: "Hiroshima", country: "Japan" },
  { code: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam" },
  { code: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam" },
  { code: "DAD", name: "Da Nang International Airport", city: "Da Nang", country: "Vietnam" },
  { code: "CNX", name: "Chiang Mai International Airport", city: "Chiang Mai", country: "Thailand" },
  { code: "HKT", name: "Phuket International Airport", city: "Phuket", country: "Thailand" },
  { code: "USM", name: "Koh Samui Airport", city: "Koh Samui", country: "Thailand" },
  { code: "DMK", name: "Don Mueang International Airport", city: "Bangkok", country: "Thailand" },
  { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
  { code: "PEN", name: "Penang International Airport", city: "Penang", country: "Malaysia" },
  { code: "JKT", name: "Soekarno–Hatta International Airport", city: "Jakarta", country: "Indonesia" },
  { code: "DPS", name: "Ngurah Rai International Airport", city: "Bali", country: "Indonesia" },
  { code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines" },
  { code: "CEB", name: "Mactan–Cebu International Airport", city: "Cebu", country: "Philippines" },
  { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", country: "India" },
  { code: "JAI", name: "Jaipur International Airport", city: "Jaipur", country: "India" },
  { code: "GOI", name: "Dabolim Airport", city: "Goa", country: "India" },
  { code: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "Nepal" },
  { code: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka" },
  { code: "MLE", name: "Velana International Airport", city: "Maldives", country: "Maldives" },
  { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
  { code: "MCT", name: "Muscat International Airport", city: "Muscat", country: "Oman" },
  { code: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel" },
  { code: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "Jordan" },
  { code: "BEY", name: "Beirut–Rafic Hariri International Airport", city: "Beirut", country: "Lebanon" },
  { code: "TBS", name: "Tbilisi International Airport", city: "Tbilisi", country: "Georgia" },
  { code: "EVN", name: "Zvartnots International Airport", city: "Yerevan", country: "Armenia" },
  { code: "BAK", name: "Heydar Aliyev International Airport", city: "Baku", country: "Azerbaijan" },
  { code: "ALA", name: "Almaty International Airport", city: "Almaty", country: "Kazakhstan" },
  { code: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh", country: "Cambodia" },
  { code: "REP", name: "Siem Reap International Airport", city: "Siem Reap", country: "Cambodia" },
  { code: "VTE", name: "Wattay International Airport", city: "Vientiane", country: "Laos" },
  { code: "LPQ", name: "Luang Prabang International Airport", city: "Luang Prabang", country: "Laos" },
  { code: "RGN", name: "Yangon International Airport", city: "Yangon", country: "Myanmar" },
  { code: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "Bangladesh" },
  { code: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "United States" },
  { code: "PDX", name: "Portland International Airport", city: "Portland", country: "United States" },
  { code: "SAN", name: "San Diego International Airport", city: "San Diego", country: "United States" },
  { code: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "United States" },
  { code: "DEN", name: "Denver International Airport", city: "Denver", country: "United States" },
  { code: "AUS", name: "Austin-Bergstrom International Airport", city: "Austin", country: "United States" },
  { code: "BNA", name: "Nashville International Airport", city: "Nashville", country: "United States" },
  { code: "MSY", name: "Louis Armstrong New Orleans International Airport", city: "New Orleans", country: "United States" },
  { code: "CHS", name: "Charleston International Airport", city: "Charleston", country: "United States" },
  { code: "SAV", name: "Savannah/Hilton Head International Airport", city: "Savannah", country: "United States" },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "United States" },
  { code: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", country: "United States" },
  { code: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "United States" },
  { code: "HOU", name: "George Bush Intercontinental Airport", city: "Houston", country: "United States" },
  { code: "IAH", name: "Houston Hobby Airport", city: "Houston", country: "United States" },
  { code: "MSP", name: "Minneapolis–Saint Paul International Airport", city: "Minneapolis", country: "United States" },
  { code: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City", country: "United States" },
  { code: "MCI", name: "Kansas City International Airport", city: "Kansas City", country: "United States" },
  { code: "SAT", name: "San Antonio International Airport", city: "San Antonio", country: "United States" },
  { code: "DTW", name: "Detroit Metropolitan Airport", city: "Detroit", country: "United States" },
  { code: "CLE", name: "Cleveland Hopkins International Airport", city: "Cleveland", country: "United States" },
  { code: "PIT", name: "Pittsburgh International Airport", city: "Pittsburgh", country: "United States" },
  { code: "CVG", name: "Cincinnati/Northern Kentucky International Airport", city: "Cincinnati", country: "United States" },
  { code: "CMH", name: "John Glenn Columbus International Airport", city: "Columbus", country: "United States" },
  { code: "IND", name: "Indianapolis International Airport", city: "Indianapolis", country: "United States" },
  { code: "MKE", name: "Milwaukee Mitchell International Airport", city: "Milwaukee", country: "United States" },
  { code: "STL", name: "St. Louis Lambert International Airport", city: "St. Louis", country: "United States" },
  { code: "BWI", name: "Baltimore/Washington International Airport", city: "Baltimore", country: "United States" },
  { code: "RIC", name: "Richmond International Airport", city: "Richmond", country: "United States" },
  { code: "RDU", name: "Raleigh-Durham International Airport", city: "Raleigh", country: "United States" },
  { code: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte", country: "United States" },
  { code: "MEM", name: "Memphis International Airport", city: "Memphis", country: "United States" },
  { code: "SDF", name: "Louisville Muhammad Ali International Airport", city: "Louisville", country: "United States" },
  { code: "TPA", name: "Tampa International Airport", city: "Tampa", country: "United States" },
  { code: "JAX", name: "Jacksonville International Airport", city: "Jacksonville", country: "United States" },
  { code: "FLL", name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale", country: "United States" },
  { code: "MIA", name: "Miami International Airport", city: "Miami", country: "United States" },
  { code: "EYW", name: "Key West International Airport", city: "Key West", country: "United States" },
  { code: "ANC", name: "Ted Stevens Anchorage International Airport", city: "Anchorage", country: "United States" },
  { code: "HNL", name: "Daniel K. Inouye International Airport", city: "Honolulu", country: "United States" },
  { code: "OGG", name: "Kahului Airport", city: "Maui", country: "United States" },
  { code: "LIH", name: "Lihue Airport", city: "Kauai", country: "United States" },
  { code: "KOA", name: "Ellison Onizuka Kona International Airport", city: "Big Island", country: "United States" },
  { code: "BOS", name: "Boston Logan International Airport", city: "Boston", country: "United States" },
  { code: "WAS", name: "Washington Dulles International Airport", city: "Washington DC", country: "United States" },
  { code: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington DC", country: "United States" },
  { code: "ORL", name: "Orlando International Airport", city: "Orlando", country: "United States" },
  { code: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", country: "United States" },
  { code: "YMQ", name: "Montreal-Pierre Elliott Trudeau International Airport", city: "Montreal", country: "Canada" },
  { code: "YQB", name: "Quebec City Jean Lesage International Airport", city: "Quebec City", country: "Canada" },
  { code: "YUL", name: "Montréal–Pierre Elliott Trudeau International Airport", city: "Montreal", country: "Canada" },
  { code: "YYC", name: "Calgary International Airport", city: "Calgary", country: "Canada" },
  { code: "YEG", name: "Edmonton International Airport", city: "Edmonton", country: "Canada" },
  { code: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "Mexico" },
  { code: "CUN", name: "Cancún International Airport", city: "Cancun", country: "Mexico" },
  { code: "GDL", name: "Guadalajara International Airport", city: "Guadalajara", country: "Mexico" },
  { code: "MTY", name: "Monterrey International Airport", city: "Monterrey", country: "Mexico" },
  { code: "PVR", name: "Puerto Vallarta International Airport", city: "Puerto Vallarta", country: "Mexico" },
  { code: "CSL", name: "Cabo San Lucas International Airport", city: "Cabo San Lucas", country: "Mexico" },
  { code: "HAV", name: "José Martí International Airport", city: "Havana", country: "Cuba" },
  { code: "SJU", name: "Luis Muñoz Marín International Airport", city: "San Juan", country: "Puerto Rico" },
  { code: "NAS", name: "Lynden Pindling International Airport", city: "Nassau", country: "Bahamas" },
  { code: "KIN", name: "Norman Manley International Airport", city: "Kingston", country: "Jamaica" },
  { code: "MBJ", name: "Sangster International Airport", city: "Montego Bay", country: "Jamaica" },
  { code: "BGI", name: "Grantley Adams International Airport", city: "Bridgetown", country: "Barbados" },
  { code: "AUA", name: "Queen Beatrix International Airport", city: "Oranjestad", country: "Aruba" },
  { code: "PUJ", name: "Punta Cana International Airport", city: "Punta Cana", country: "Dominican Republic" },
  { code: "SJO", name: "Juan Santamaría International Airport", city: "San Jose", country: "Costa Rica" },
  { code: "LIR", name: "Daniel Oduber Quirós International Airport", city: "Liberia", country: "Costa Rica" },
  { code: "PTY", name: "Tocumen International Airport", city: "Panama City", country: "Panama" },
  { code: "BZE", name: "Philip S. W. Goldson International Airport", city: "Belize City", country: "Belize" },
  { code: "GUA", name: "La Aurora International Airport", city: "Guatemala City", country: "Guatemala" },
  { code: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "Colombia" },
  { code: "MDE", name: "José María Córdova International Airport", city: "Medellín", country: "Colombia" },
  { code: "CTG", name: "Rafael Núñez International Airport", city: "Cartagena", country: "Colombia" },
  { code: "CLO", name: "Alfonso Bonilla Aragón International Airport", city: "Cali", country: "Colombia" },
  { code: "SMR", name: "Simón Bolívar International Airport", city: "Santa Marta", country: "Colombia" },
  { code: "UIO", name: "Mariscal Sucre International Airport", city: "Quito", country: "Ecuador" },
  { code: "GPS", name: "Seymour Airport", city: "Galapagos Islands", country: "Ecuador" },
  { code: "LPB", name: "El Alto International Airport", city: "La Paz", country: "Bolivia" },
  { code: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "Peru" },
  { code: "CUZ", name: "Alejandro Velasco Astete International Airport", city: "Cusco", country: "Peru" },
  { code: "AQP", name: "Rodríguez Ballón International Airport", city: "Arequipa", country: "Peru" },
  { code: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina" },
  { code: "AEP", name: "Aeroparque Jorge Newbery", city: "Buenos Aires", country: "Argentina" },
  { code: "MDZ", name: "Governor Francisco Gabrielli International Airport", city: "Mendoza", country: "Argentina" },
  { code: "BRC", name: "San Carlos de Bariloche Airport", city: "Bariloche", country: "Argentina" },
  { code: "USH", name: "Malvinas Argentinas Ushuaia International Airport", city: "Ushuaia", country: "Argentina" },
  { code: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "Chile" },
  { code: "CJC", name: "El Loa Airport", city: "Calama", country: "Chile" },
  { code: "PUQ", name: "Presidente Carlos Ibáñez del Campo International Airport", city: "Punta Arenas", country: "Chile" },
  { code: "GIG", name: "Rio de Janeiro–Galeão International Airport", city: "Rio de Janeiro", country: "Brazil" },
  { code: "GRU", name: "São Paulo/Guarulhos International Airport", city: "Sao Paulo", country: "Brazil" },
  { code: "SSA", name: "Deputado Luís Eduardo Magalhães International Airport", city: "Salvador", country: "Brazil" },
  { code: "REC", name: "Recife/Guararapes International Airport", city: "Recife", country: "Brazil" },
  { code: "FLN", name: "Hercílio Luz International Airport", city: "Florianópolis", country: "Brazil" },
  { code: "IGU", name: "Cataratas International Airport", city: "Iguazu Falls", country: "Brazil" },
  { code: "BSB", name: "Brasília International Airport", city: "Brasilia", country: "Brazil" },
  { code: "FOR", name: "Pinto Martins International Airport", city: "Fortaleza", country: "Brazil" },
  { code: "MAO", name: "Eduardo Gomes International Airport", city: "Manaus", country: "Brazil" },
  { code: "MVD", name: "Carrasco International Airport", city: "Montevideo", country: "Uruguay" },
  { code: "ASU", name: "Silvio Pettirossi International Airport", city: "Asunción", country: "Paraguay" },
  { code: "CCS", name: "Simón Bolívar International Airport", city: "Caracas", country: "Venezuela" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { code: "ZQN", name: "Queenstown Airport", city: "Queenstown", country: "New Zealand" },
  { code: "WLG", name: "Wellington International Airport", city: "Wellington", country: "New Zealand" },
  { code: "CHC", name: "Christchurch International Airport", city: "Christchurch", country: "New Zealand" },
  { code: "NAN", name: "Nadi International Airport", city: "Nadi", country: "Fiji" },
  { code: "PPT", name: "Fa'a'ā International Airport", city: "Papeete", country: "French Polynesia" },
  { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
  { code: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia" },
  { code: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "Australia" },
];

// Helper functions
export function searchCities(query: string, limit: number = 10): CityData[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return CITIES.filter((city) =>
    city.name.toLowerCase().includes(q) ||
    city.country.toLowerCase().includes(q) ||
    city.region.toLowerCase().includes(q) ||
    city.airportCode?.toLowerCase().includes(q)
  ).slice(0, limit);
}

export function searchAirports(query: string, limit: number = 10) {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return AIRPORTS.filter((airport) =>
    airport.code.toLowerCase().includes(q) ||
    airport.name.toLowerCase().includes(q) ||
    airport.city.toLowerCase().includes(q) ||
    airport.country.toLowerCase().includes(q)
  ).slice(0, limit);
}

export function getGoogleFlightsUrl(
  originAirport: string,
  destinationAirport: string,
  monthKey?: string
): string {
  const params = new URLSearchParams();
  let query = "";
  
  if (originAirport && destinationAirport) {
    query = `${originAirport} to ${destinationAirport}`;
  } else if (destinationAirport) {
    query = `to ${destinationAirport}`;
  } else if (originAirport) {
    query = `from ${originAirport}`;
  }
  
  if (monthKey && query) {
    const [year, month] = monthKey.split("-");
    const departureDate = `${year}-${month}-15`;
    query += ` ${departureDate}`;
  }
  
  params.set("q", query);
  return `https://www.google.com/travel/flights?${params.toString()}`;
}

export function getAvatarGradient(name: string): string {
  const gradients = [
    "from-blue-500 to-indigo-600",
    "from-purple-500 to-pink-600",
    "from-green-500 to-teal-600",
    "from-orange-500 to-red-600",
    "from-cyan-500 to-blue-600",
    "from-rose-500 to-pink-600",
    "from-amber-500 to-orange-600",
    "from-emerald-500 to-green-600",
  ];
  const hash = name.split("").reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return gradients[hash % gradients.length];
}

export function getSeasonLabel(monthNumber: number, destination: CityData): { label: string; color: string; icon?: string } {
  // Check which season this month falls into for the destination
  const isPeakSeason = destination.bestMonths?.includes(monthNumber);
  const isShoulderSeason = destination.shoulderMonths?.includes(monthNumber);
  
  if (isPeakSeason) {
    return {
      label: "Peak Season",
      color: "border-green-500/50 bg-green-50 text-green-700",
      icon: "🔥"
    };
  }
  
  if (isShoulderSeason) {
    return {
      label: "Shoulder Season",
      color: "border-yellow-500/50 bg-yellow-50 text-yellow-700",
      icon: "⭐"
    };
  }
  
  return {
    label: "Off Season",
    color: "border-blue-500/50 bg-blue-50 text-blue-700",
    icon: "❄️"
  };
}

export function isVisaFreeForUS(countryCode: string): boolean {
  const visaFreeCountries = new Set([
    "FR", "IT", "ES", "PT", "DE", "UK", "IE", "NL", "BE", "CH", "AT", "DK", "SE", "NO", "FI", "IS",
    "GR", "HR", "CZ", "HU", "PL", "EE", "LV", "LT", "SI", "SK", "JP", "KR", "SG", "MY", "TH", "AU",
    "NZ", "CA", "MX", "CR", "PA", "CL", "AR", "UY", "BR", "IL", "AE", "QA", "BH", "OM", "KW"
  ]);
  return visaFreeCountries.has(countryCode);
}
